version: '2.1'

services:

  neurosynth:
    build: .
    restart: always
    ports:
      - "8000"
    volumes:
      - .:/code
      - ./data:/data:rw
      - ./logs:/logs:rw
    working_dir: /code
    command: /code/scripts/docker_startup.sh
    depends_on:
      - db
      - redis

  db:
    restart: always
    image: postgres:10.4
    expose:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=neurosynth
      - POSTGRES_USER=neurosynth

  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
    volumes_from:
      - neurosynth
    depends_on:
      - neurosynth

  redis:
    restart: always
    image: redis:latest
    sysctls:
      net.core.somaxconn: '511'

  worker:
    image: nsweb_neurosynth:latest
    restart: always
    working_dir: /code
    command: /code/scripts/run_celery.sh
    volumes_from:
      - neurosynth
    depends_on:
      - db
      - redis

volumes:
  postgres-data:
  redis-data:
